name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
  workflow_dispatch:

jobs:
  build:    
    runs-on: ubuntu-latest
    
    steps:      
      - uses: actions/checkout@v3
      
      - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
      - name: Docker Build And Push
        uses: docker/build-push-actions@2.289.2
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            ricellirousselet/rotten-potatoes:latest
            ricellirousselet/rotten-potatoes:${{ github.run_number }}
